<h1>An error occurred</h1>
<h2><?php echo $this->message ?></h2>

<?php /** @var Exception $this->exception */ ?>
<?php if (isset($this->exception)): ?>

<h3>Exception information:</h3>
<p>
  <b>Message:</b> <?php echo $this->exception->getMessage() ?>
</p>

<h3>Stack trace:</h3>
<ol class="stackTrace">
	<?php foreach ($this->exception->getTrace() as $traceItem): ?>
	<?php
		$argString = '';
		if (! empty($traceItem['args'])) {
			$arg = $traceItem['args'][0];
			if (is_string($arg)) {
				$argString = $arg;
			}
			elseif (is_object($arg)) {
				$argString = get_class($arg);
			}
		}
	?>
	<li>
		<?php echo $traceItem['file']; ?> (<?php echo $traceItem['line']; ?>)
		<div class="method">-><span class="bold"><?php echo $traceItem['function']; ?></span>(<?php echo $argString; ?>)</div>
	</li>
	<?php endforeach; ?>
</ol>

<pre><?php // echo $this->exception->getTraceAsString(); ?></pre>

<h3>Request Parameters:</h3>
<pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
</pre>

<?php endif ?>