<?php include 'inc/htmlHeader.phtml'; ?>
<div id="sitewrapper">
	<div id="overlay"></div>

	<div id="pagewrapper">
		<header><h1>[HEADER]</h1></header>

		<aside>
			<?php include 'inc/navigation.phtml'; ?>
		</aside>

		<div id="content">

<h2>Bücher</h2>

<div id="medialist" class="books">
	<div class="row">
		<div class="book left">
			<div class="thumb">
				<img src="/img/books/der.unsterbliche.alchemist_small.jpg" alt="Der unsterbliche Alchemist">
			</div>
			<div class="info">
				<div class="title" colspan="2">Die Geheimnisse des Nicholas Flamel - Der unsterbliche Alchemist</div>
				<div class="release">Erscheinungsjahr: 2008 (1. Auflage)</div>
				<div class="author">Autor: Michael Scott</div>
			</div>
		</div>
		<div class="book right">
			<div class="thumb">
				<img src="/img/books/der.dunkle.magier_small.jpg" alt="Der unsterbliche Alchemist">
			</div>
			<div class="info">
				<div class="title" colspan="2">Die Geheimnisse des Nicholas Flamel - Der dunkle Magier</div>
				<div class="release">Erscheinungsjahr: 2009 (2. Auflage)</div>
				<div class="author">Autor: Michael Scott</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="book left">
			<div class="thumb">
				<img src="/img/books/der.unsterbliche.alchemist_small.jpg" alt="Der unsterbliche Alchemist">
			</div>
			<div class="info">
				<div class="title" colspan="2">Die Geheimnisse des Nicholas Flamel - Der unsterbliche Alchemist</div>
				<div class="release">Erscheinungsjahr: 2008 (1. Auflage)</div>
				<div class="author">Autor: Michael Scott</div>
			</div>
		</div>
		<div class="book right">
			<div class="thumb">
				<img src="/img/books/der.dunkle.magier_small.jpg" alt="Der unsterbliche Alchemist">
			</div>
			<div class="info">
				<div class="title" colspan="2">Die Geheimnisse des Nicholas Flamel - Der dunkle Magier</div>
				<div class="release">Erscheinungsjahr: 2009 (2. Auflage)</div>
				<div class="author">Autor: Michael Scott</div>
			</div>
		</div>
	</div>
</div>

		</div>

		<footer>
			[FOOTER]
			<a href="/workfiles/" class="wfLink">Workfiles</a>
		</footer>
	</div>

	<div id="layer"></div>
</div>
<?php include 'inc/htmlFooter.phtml'; ?>
