<?php include 'inc/htmlHeader.phtml'; ?>
<div id="sitewrapper">
	<div id="overlay"></div>

	<div id="pagewrapper">
		<header><h1>[HEADER]</h1></header>

		<aside>
			<?php include 'inc/navigation.phtml'; ?>
		</aside>

		<div id="content">

<h2>Film editieren</h2>

<form id="mediaForm" action="/add-movie" method="post">
	<fieldset class="general">
		<legend>Generelle Infos</legend>
		<dl>
			<dt class="fieldLbl"><label for="title">Titel</label></dt>
			<dd><input id="title" name="title" type="text"></dd>
			<dt class="fieldLbl"><label for="original_title">Originaltitel</label></dt>
			<dd><input id="original_title" name="original_title" type="text"></dd>
			<dt class="textareaLbl"><label for="blurb">Klappentext</label></dt>
			<dd><textarea id="blurb" name="blurb" rows="1" cols="1"></textarea></dd>
		</dl>
	</fieldset>
	<fieldset class="additional">
		<legend>Zusätzliche Infos</legend>
		<dl>
			<dt class="fieldLbl"><label for="medium">Medium</label></dt>
			<dd><input id="medium" name="medium" type="text"></dd>
			<dt class="fieldLbl"><label for="genre">Genre</label></dt>
			<dd><input id="genre" name="genre" type="text"></dd>
			<dt class="fieldLbl"><label for="director">Regie</label></dt>
			<dd><input id="director" name="director" type="text"></dd>
			<dt class="textareaLbl"><label for="writers">Drehbuch</label></dt>
			<dd><textarea id="writers" name="actors" rows="1" cols="1"></textarea></dd>
			<dt class="textareaLbl"><label for="actors">Darsteller</label></dt>
			<dd><textarea id="actors" name="actors" rows="1" cols="1"></textarea></dd>
		</dl>
	</fieldset>
	<fieldset class="formCtrl">
		<ul>
			<li><button id="subtmit" class="green">Speichern</button></li>
			<li><button id="cancel" class="red">Abbrechen</button></li>
		</ul>
	</fieldset>
</form>

		</div>

		<footer>
			[FOOTER]
			<a href="/workfiles/" class="wfLink">Workfiles</a>
		</footer>
	</div>

	<div id="layer"></div>
</div>
<?php include 'inc/htmlFooter.phtml'; ?>