<?php include 'inc/htmlHeader.phtml'; ?>
<div id="sitewrapper">
	<div id="overlay"></div>

	<div id="pagewrapper">
		<header><h1>[HEADER]</h1></header>

		<aside>
			<?php include 'inc/navigation.phtml'; ?>
		</aside>

		<div id="content">

<h2>Buch editieren</h2>

<form id="mediaForm" action="/add-book" method="post">
	<fieldset class="general">
		<legend>Generelle Infos</legend>
		<dl>
			<dt class="inputLbl"><label for="title">Titel</label></dt>
			<dd><input id="title" name="title" type="text"></dd>
			<dt class="inputLbl"><label for="original_title">Originaltitel</label></dt>
			<dd><input id="original_title" name="original_title" type="text"></dd>
			<dt class="textareaLbl"><label for="blurb">Klappentext</label></dt>
			<dd><textarea id="blurb" name="blurb" cols="1" rows="1"></textarea></dd>


		</dl>
	</fieldset>
	<fieldset class="additional">
		<legend>Zusätzliche Infos</legend>
		<dl>
			<dt class="inputLbl"><label for="publisher">Verlag</label></dt>
			<dd><input id="publisher" name="publisher" type="text"></dd>
			<dt class="textareaLbl"><label for="authors">Autoren</label></dt>
			<dd><textarea id="authors" name="authors" cols="1" rows="1"></textarea></dd>
		</dl>
	</fieldset>
	<fieldset class="formCtrl">
		<ul>
			<li><button id="subtmit" class="green">Speichern</button></li>
			<li><button id="cancel" class="red">Abbrechen</button></li>
		</ul>
	</fieldset>
</form>

		</div>

		<footer>
			[FOOTER]
			<a href="/workfiles/" class="wfLink">Workfiles</a>
		</footer>
	</div>

	<div id="layer"></div>
</div>
<?php include 'inc/htmlFooter.phtml'; ?>