<?php include 'inc/htmlHeader.phtml'; ?>
<div id="sitewrapper">
	<div id="overlay"></div>

	<div id="pagewrapper">
		<header><h1>[HEADER]</h1></header>

		<aside>
			<?php include 'inc/navigation.phtml'; ?>
		</aside>

		<div id="content">

<h2>Filme</h2>

<div id="medialist" class="movies">
	<div class="row">
		<div class="movie left">
			<div class="thumb">
				<img src="/img/movies/tron_small.png" alt="Tron (1982)">
			</div>
			<div class="loaned">
				<div class="loanedIcon">[v]</div>
			</div>
			<div class="info">
				<table>
					<tr>
						<td class="title" colspan="2">TRON</td>
					</tr>
					<tr><td class="release" colspan="2">(1979)</td></tr>
					<tr class="written">
						<td class="lbl">Drehbuch:</td>
						<td class="val">
							Gene Roddenberry,<br>
							Alan Dean Foster,<br>
							Harold Livingston
						</td>
					</tr>
					<tr class="directed">
						<td class="lbl">Regie:</td>
						<td class="val">Robert Wise</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="movie right">
			<div class="thumb">
				<img src="/img/movies/star.trek.the.motion.picture_small.png" alt="Tron (1979)">
			</div>
			<div class="info">
				<table>
					<tr>
						<td class="title" colspan="2">Star Trek: The Motion Picture</td>
					</tr>
					<tr>
						<td class="release" colspan="2">(1979)</td>
					</tr>
					<tr class="written">
						<td class="lbl">Drehbuch:</td>
						<td class="val">Steven Lisberger</td>
					</tr>
					<tr class="directed">
						<td class="lbl">Regie:</td>
						<td class="val">Steven Lisberger</td>
					</tr>
				</table>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="movie left">
			<div class="thumb">
				<img src="/img/movies/star.trek.the.wrath.of.khan_small.jpg" alt="Star Trek II: The Wrath of Khan (1982)">
			</div>
			<div class="info">
				<table>
					<tr>
						<td class="title" colspan="2">Star Trek II: The Wrath of Khan</td>
					</tr>
					<tr>
						<td class="release" colspan="2">(1982)</td>
					</tr>
					<tr class="written">
						<td class="lbl">Drehbuch:</td>
						<td class="val">
							Jack B. Sowards,<br>
							Nicholas Meyer
						</td>
					</tr>
					<tr class="directed">
						<td class="lbl">Regie:</td>
						<td class="val">Nicholas Meyer</td>
					</tr>
				</table>
			</div>
		</div>
		<div class="movie right">
			<div class="thumb">
				<img src="/img/movies/star.trek.the.search.for.spock_small.jpg" alt="Star Trek III: The Search For Spock (1984)">
			</div>
			<div class="info">
				<table>
					<tr>
						<td class="title" colspan="2">Star Trek III: The Search For Spock</td>
					</tr>
					<tr>
						<td class="release" colspan="2">(1984)</td>
					</tr>
					<tr class="written">
						<td class="lbl">Drehbuch:</td>
						<td class="val">Harve Bennett</td>
					</tr>
					<tr class="directed">
						<td class="lbl">Regie:</td>
						<td class="val">Leonard Nimoy</td>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>

		</div>

		<footer>
			[FOOTER]
			<a href="/workfiles/" class="wfLink">Workfiles</a>
		</footer>
	</div>

	<div id="layer"></div>
</div>
<?php include 'inc/htmlFooter.phtml'; ?>
