<?php include 'inc/htmlHeader.phtml'; ?>
<div id="sitewrapper">
	<div id="overlay"></div>

	<div id="pagewrapper">
		<header><h1>[HEADER]</h1></header>

		<aside>
			<?php include 'inc/navigation.phtml'; ?>
		</aside>

		<div id="content">

<h2>Wunschliste</h2>

<div id="wishlist">
	<div class="item">
		<div class="title">Ronja Räubertochter</div>
		<div class="info">
			Film von 1984;
		</div>
	</div>
	<div class="item">
		<div class="title">Der unsterbliche Alchemist - Der schwarze Hexenmeister</div>
		<div class="info">
			Buch von 2011, ISBN 978-3-570-15433-5.
		</div>
	</div>
</div>

		</div>

		<footer>
			[FOOTER]
			<a href="/workfiles/" class="wfLink">Workfiles</a>
		</footer>
	</div>

	<div id="layer"></div>
</div>
<?php include 'inc/htmlFooter.phtml'; ?>
