[production]
phpSettings.display_startup_errors = 0
phpSettings.display_errors = 0

; +++ paths +++

includePaths.library = APPLICATION_PATH "/../library"
configPath = APPLICATION_PATH "/configs/"


; +++ bootstrap +++

bootstrap.path = APPLICATION_PATH "/Bootstrap.php"
bootstrap.class = "Bootstrap"


; +++ front controller +++

resources.frontController.controllerDirectory = APPLICATION_PATH "/controllers"
resources.frontController.actionhelperpaths.Foo_Controller_Action_Helper = "Foo/Controller/Action/Helper"


; +++ locale +++

resources.locale.default = "de_DE.utf8"
resources.locale.force = true


; +++ layout & view +++

resources.layout.layoutPath = APPLICATION_PATH "/layouts/scripts"
resources.layout.default = "standard"


; +++ autoloader +++

autoloaderNamespaces[] = "Foo_"
autoloaderNamespaces[] = "Pollux_"

autoloader.basePath = APPLICATION_PATH
autoloader.namespace =

autoloader.resourceTypes.controller.path = "library"
autoloader.resourceTypes.controller.namespace = ""

;autoloader.resourceTypes.library.path = "Foo"
;autoloader.resourceTypes.library.namespace = "Foo"

autoloader.resourceTypes.model.path = "models"
autoloader.resourceTypes.model.namespace = "Model"

autoloader.resourceTypes.forms.path = "forms"
autoloader.resourceTypes.forms.namespace = "Form"


; +++ error logging +++

resources.log.stream.writerName = "Stream"
resources.log.stream.writerParams.stream = APPLICATION_PATH . "/../logs/php.log"
resources.log.stream.writerParams.mode = "a"



; +++ database +++

resources.db.adapter = "PDO_MYSQL"
resources.db.params.host = "localhost"
resources.db.params.dbname = "pollux"
resources.db.params.username = "develuser"
resources.db.params.password = "develpwd"
resources.db.params.driver_options.1002 = "SET NAMES UTF8;"
resources.db.isDefaultTableAdapter = true



[staging : production]



[testing : production]
phpSettings.display_startup_errors = 1
phpSettings.display_errors = 1



[development : production]
phpSettings.display_startup_errors = 1
phpSettings.display_errors = 1



; +++ front controller +++

resources.frontController.params.displayExceptions = 1


; +++ error logging +++

resources.log.stream.writerName = "Firebug"
