[production]

home.label = "Home"
home.controller = "index"
home.action = "index"

movies.label = "Filme"
movies.controller = "movie"
movies.action = "index"
movies.url = "/movies/"

books.label = "Bücher"
books.controller = "book"
books.action = "index"
books.url = "/books/"


addmovie.label = "Film hinzufügen"
addmovie.controller = "movie"
addmovie.action = "add"
addmovie.url = "/add/movie/"

addbook.label = "Buch hinzufügen"
addbook.controller = "book"
addbook.action = "add"
addbook.url = "/add/book/"

adduser.label = "Person hinzufügen"
adduser.controller = "user"
adduser.action = "add"
adduser.url = "/add/user/"



[development : production]

;workfiles.label = "Workfiles"
;workfiles.url = "/workfiles/"
