<nav id="navigation">
	<div class="mainnav">
		<ul>
			<li class="active"><a href="/">Home</a></li>
			<li><a href="javascript:;">Filme</a></li>
			<li><a href="javascript:;">Bücher</a></li>
			<li><a href="javascript:;">Admin</a></li>
		</ul>
		<div class="clear"></div>
	</div>
	<div id="adminnav">
		<ul>
			<li><a href="javascript:;">Filme</a></li>
			<li><a href="javascript:;">Bücher</a></li>
			<li><a href="javascript:;">Medientypen</a></li>
			<li><a href="javascript:;">Benutzer</a></li>
			<li><a href="javascript:;">Wunschliste</a></li>
		</ul>
		<div class="clear"></div>
	</div>

</nav>

