<div class="pagination">
	<div class="inner">
		<div>
			<span class="first"><img src="/skins/default/icons/16/control_start.png" alt="erste seite" title="Zur ersten Seite"></span>
			<span class="prev"><img src="/skins/default/icons/16/control_prev.png" alt="vorherige seite" title="Zur vorherigen Seite"></span>
		</div>
		<ul class="pagenumbers">
			<li>1</li>
			<li>2</li>
			<li>3</li>
			<li class="active">4</li>
			<li>5</li>
			<li>6</li>
			<li>7</li>
			<li>8</li>
			<li>9</li>
			<li>10</li>
		</ul>
		<div>
			<a class="next" href="javascript:;"><img src="/skins/default/icons/16/control_play_blue.png" alt="nächste seite" title="Zur nächsten Seite"></a>
			<a class="last" href="javasctipt:;"><img src="/skins/default/icons/16/control_end_blue.png" alt="letzte seite" title="Zur letzten Seite"></a>
		</div>
	</div>
</div>