<nav id="mainnav">
	<div class="head">:: MAINNAVIGATION ::</div>
	<ul>
		<li><a href="/">Home</a></li>
		<li><a href="/movies/">Filme</a></li>
		<li><a href="/books/">Bücher</a></li>
	</ul>
</nav>

<nav id="adminnav">
	<div class="head">:: ADMINISTRATION ::</div>
	<ul>
		<li><a href="/movie/add/">Film hinzufügen</a></li>
		<li><a href="/book/add/">Buch hinzufügen</a></li>
		<li><a href="/user/add/">Person hinufügen</a></li>
		<li><a href="/wishlist/">Wunschliste</a></li>
	</ul>
</nav>
