<nav id="mainnav">
	<div class="head">:: MAINNAVIGATION ::</div>
	<ul>
		<li><a href="/">Home</a></li>
		<li><a href="/movies/">Filme</a></li>
		<li><a href="/books/">Bücher</a></li>
	</ul>
</nav>

<nav id="adminnav">
	<div class="head">:: ADMINISTRATION ::</div>
	<ul>
		<li><a href="/workfiles/edit-movie.phtml">Film hinzufügen</a></li>
		<li><a href="/workfiles/edit-book.phtml">Buch hinzufügen</a></li>
		<li><a href="/workfiles/edit-person.phtml">Person hinufügen</a></li>
		<li><a href="/workfiles/wishlist.phtml">Wunschliste</a></li>
	</ul>
</nav>
