<?php include 'inc/header.phtml'; ?>
<h2>Filme</h2>

<div id="medialist" class="movies">
	<table>
		<tr>
			<th class="title">titel</th>
			<th class="oTitle">originaltitel</th>
			<th class="release">release</th>
			<th class="actions"></th>
		</tr>
		<tr>
			<td class="title">TRON</td>
			<td class="oTitle">TRON</td>
			<td class="release">1979</td>
			<td class="actions">
				<a href="javascript:;"><img src="/skins/default/icons/16/magnifier.png" alt="details button" title="Details anzeigen"></a>
				<a href="javascript:;"><img src="/skins/default/icons/16/pencil.png" alt="edit button" title="Bearbeiten"></a>
			</td>
		</tr>
		<tr>
			<td class="title">Star Trek: Der Film</td>
			<td class="oTitle">Star Trek: The Motion Picture</td>
			<td class="release">1979</td>
			<td class="actions">
				<a href="javascript:;"><img src="/skins/default/icons/16/magnifier.png" alt="details button" title="Details anzeigen"></a>
				<a href="javascript:;"><img src="/skins/default/icons/16/pencil.png" alt="edit button" title="Bearbeiten"></a>
			</td>
		</tr>
		<tr>
			<td class="title">Star Trek II: Der Zorn des Khan</td>
			<td class="oTitle">Star Trek II: The Wrath of Khan</td>
			<td class="release">1982</td>
			<td class="actions">
				<a href="javascript:;"><img src="/skins/default/icons/16/magnifier.png" alt="details button" title="Details anzeigen"></a>
				<a href="javascript:;"><img src="/skins/default/icons/16/pencil.png" alt="edit button" title="Bearbeiten"></a>
			</td>
		</tr>
		<tr>
			<td class="title">Star Trek III: Auf der Suche nach Mr. Spock</td>
			<td class="oTitle">Star Trek III: The Search For Spock</td>
			<td class="release">1984</td>
			<td class="actions">
				<a href="javascript:;"><img src="/skins/default/icons/16/magnifier.png" alt="details button" title="Details anzeigen"></a>
				<a href="javascript:;"><img src="/skins/default/icons/16/pencil.png" alt="edit button" title="Bearbeiten"></a>
			</td>
		</tr>
	</table>

	<?php include 'inc/pagination.phtml'; ?>
</div>

<?php include 'inc/footer.phtml'; ?>
<?php include 'inc/htmlFooter.phtml'; ?>
